// src/lib/pdfGen.js
// ─────────────────────────────────────────────────────────────────────────────
// Professional PDF generation from resume text using jsPDF
// ─────────────────────────────────────────────────────────────────────────────

const PAGE_CONFIG = {
  format: 'letter',        // 8.5" × 11"
  unit: 'pt',
  marginX: 60,
  marginY: 55,
  lineHeight: {
    section: 18,
    bullet: 13.5,
    normal: 14,
    gap: 7,
  },
  fonts: {
    header: { size: 11, style: 'bold' },
    name: { size: 16, style: 'bold' },
    contact: { size: 9.5, style: 'normal' },
    body: { size: 10, style: 'normal' },
    bullet: { size: 9.5, style: 'normal' },
    sectionLabel: { size: 10, style: 'bold' },
  }
};

/**
 * Classify a line type for styling
 */
function classifyLine(line) {
  const t = line.trim();
  if (!t) return 'empty';
  if (t === t.toUpperCase() && t.length > 2 && !/^\d/.test(t) && !/[@.]/.test(t)) return 'section';
  if (/^[•\-\*>]/.test(t)) return 'bullet';
  if (/^[A-Z][^a-z]{0,30}\|/.test(t) || /^\d{4}/.test(t)) return 'meta';
  return 'normal';
}

/**
 * Generate a formatted PDF from resume text
 * @param {string} resumeText - Plain text resume content
 * @param {string} filename - Output filename
 */
export function generateResumePDF(resumeText, filename = 'optimized-resume.pdf') {
  if (!window.jspdf) throw new Error('jsPDF not loaded');
  
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: PAGE_CONFIG.unit, format: PAGE_CONFIG.format });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const { marginX, marginY, lineHeight } = PAGE_CONFIG;
  const maxWidth = pageW - marginX * 2;

  let y = marginY;
  let isFirstSection = true;

  const checkPageBreak = (needed = 20) => {
    if (y + needed > pageH - marginY) {
      doc.addPage();
      y = marginY;
      return true;
    }
    return false;
  };

  const lines = resumeText.split('\n');

  lines.forEach((rawLine) => {
    const type = classifyLine(rawLine);
    const text = rawLine.trim();

    switch (type) {
      case 'empty':
        y += lineHeight.gap;
        break;

      case 'section': {
        if (!isFirstSection) y += lineHeight.gap * 1.5;
        checkPageBreak(28);
        
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(30, 30, 30);
        doc.text(text, marginX, y);
        
        // Underline rule
        doc.setDrawColor(180, 155, 80);
        doc.setLineWidth(0.75);
        doc.line(marginX, y + 3, pageW - marginX, y + 3);
        
        y += lineHeight.section;
        isFirstSection = false;
        break;
      }

      case 'bullet': {
        checkPageBreak(16);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9.5);
        doc.setTextColor(40, 40, 40);
        
        const bulletContent = '• ' + text.replace(/^[•\-\*>]\s*/, '');
        const wrapped = doc.splitTextToSize(bulletContent, maxWidth - 12);
        
        wrapped.forEach((wl, idx) => {
          checkPageBreak(14);
          doc.text(wl, marginX + (idx === 0 ? 0 : 10), y);
          y += lineHeight.bullet;
        });
        break;
      }

      case 'meta': {
        checkPageBreak(14);
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(9.5);
        doc.setTextColor(80, 80, 80);
        const wrapped = doc.splitTextToSize(text, maxWidth);
        wrapped.forEach(wl => {
          checkPageBreak(14);
          doc.text(wl, marginX, y);
          y += lineHeight.normal;
        });
        break;
      }

      default: { // normal
        checkPageBreak(14);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(30, 30, 30);
        const wrapped = doc.splitTextToSize(text, maxWidth);
        wrapped.forEach(wl => {
          checkPageBreak(14);
          doc.text(wl, marginX, y);
          y += lineHeight.normal;
        });
      }
    }
  });

  // Footer on each page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(`Page ${i} of ${totalPages}`, pageW / 2, pageH - 24, { align: 'center' });
    doc.text('Generated by AI Resume Editor', pageW - marginX, pageH - 24, { align: 'right' });
  }

  doc.save(filename);
}
